version: 2
updates:
- package-ecosystem: maven
  directory: "/."
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-maven-plugin
    versions:
    - 2.4.1
    - 2.4.2
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - 2.4.1
    - 2.4.2
  - dependency-name: org.testcontainers:testcontainers-bom
    versions:
    - 1.15.1
  - dependency-name: org.assertj:assertj-core
    versions:
    - 3.18.1
